/*Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (1, 'String', 'String');
Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (2, 'Number', 'Number');
Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (3, 'List', 'List');
Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (4, 'Date', 'Date');
Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (5, 'DateTime', 'DateTime');
Insert into ITEM_ATTR_TYPE_DATATYPE
   (ITEM_ATTR_TYPE_DATATYPE_CODE, ITEM_ATTR_TYPE_DATATYPE_NAME, ITEM_ATTR_TYPE_DATATYPE_DESC)
 Values
   (6, 'Image', 'Image');
COMMIT;
*/


