
/*
CREATE TABLE ITEM_ATTRIBUTE
(
  ITEM_ATTR_ID       VARCHAR(32)          NOT NULL,
  ITEM_ATTR_VALUE    VARCHAR(256),
  ITEM_ATTR_TYPE_ID  VARCHAR(32)          NOT NULL,
  ITEM_ID            VARCHAR(32)          NOT NULL,
  PRIMARY KEY ( ITEM_ATTR_ID)
);



CREATE TABLE IMPORT_JOBS
(
  FILENAME   VARCHAR(250),
  STATUS     VARCHAR(1),
  STARTTIME  DATE,
  ENDTIME    DATE,
  PRIMARY KEY(FILENAME)
);


CREATE TABLE RELATIONSHIP_TYPE
(
  REL_TYPE_ID    VARCHAR(32)              NOT NULL,
  REL_TYPE_CODE  VARCHAR(64)              NOT NULL,
  REL_TYPE_NAME  VARCHAR(128)             NOT NULL,
  REL_TYPE_DESC  VARCHAR(256),
  PRIMARY KEY (REL_TYPE_ID)
);

CREATE TABLE ITEM_RELATIONSHIP_RULE_BASE
(
  ITEM_REL_RULE_BASE_ID    VARCHAR(32)    NOT NULL,
  SOURCE_ITEM_TYPE_ID      VARCHAR(32)    NOT NULL,
  TARGET_ITEM_TYPE_ID      VARCHAR(32)    NOT NULL,
  REL_TYPE_ID              VARCHAR(32)    NOT NULL,
  ITEM_REL_RULE_BASE_DESC  VARCHAR(256)   NOT NULL,
  PRIMARY KEY (ITEM_REL_RULE_BASE_ID));



CREATE TABLE RELATIONSHIP_ATTRIBUTE_TYPE
(
  REL_ATTR_TYPE_ID    VARCHAR(32)         NOT NULL,
  REL_ATTR_TYPE_CODE  VARCHAR(64)         NOT NULL,
  REL_ATTR_TYPE_NAME  VARCHAR(128)        NOT NULL,
  REL_ATTR_TYPE_DESC  VARCHAR(256),
  REL_TYPE_ID         VARCHAR(32)         NOT NULL,
  PRIMARY KEY(REL_ATTR_TYPE_ID)
);


CREATE TABLE ITEM_TYPE
(
  ITEM_TYPE_ID    VARCHAR(32)             NOT NULL,
  ITEM_TYPE_CODE  VARCHAR(64)             NOT NULL,
  ITEM_TYPE_NAME  VARCHAR(128)            NOT NULL,
  ITEM_TYPE_DESC  VARCHAR(256),
  PRIMARY KEY(ITEM_TYPE_ID)
);


CREATE TABLE RELATIONSHIP
(
  REL_ID       VARCHAR(32)                NOT NULL,
  REL_NAME     VARCHAR(128)               NOT NULL,
  REL_DESC     VARCHAR(256),
  REL_TYPE_ID  VARCHAR(32)                NOT NULL,
  PRIMARY KEY (REL_ID)
);


CREATE TABLE RELATIONSHIP_MAPPING
(
  SOURCE_ITEM_ID  VARCHAR(32)             NOT NULL,
  TARGET_ITEM_ID  VARCHAR(32)             NOT NULL,
  REL_ID          VARCHAR(32)             NOT NULL,
  PRIMARY KEY (REL_ID, SOURCE_ITEM_ID, TARGET_ITEM_ID)
);



CREATE TABLE RELATIONSHIP_ATTRIBUTE
(
  REL_ATTR_ID       VARCHAR(32)           NOT NULL,
  REL_ATTR_VALUE    VARCHAR(256),
  REL_ID            VARCHAR(32)           NOT NULL,
  REL_ATTR_TYPE_ID  VARCHAR(32)           NOT NULL,
  PRIMARY KEY (REL_ATTR_ID)
);



CREATE TABLE ITEM_ATTRIBUTE_TYPE
(
  ITEM_ATTR_TYPE_ID               VARCHAR(32) NOT NULL,
  ITEM_ATTR_TYPE_CODE             VARCHAR(64) NOT NULL,
  ITEM_ATTR_TYPE_NAME             VARCHAR(128) NOT NULL,
  ITEM_ATTR_TYPE_DESC             VARCHAR(256),
  ITEM_ATTR_TYPE_DATATYPE_CODE    NUMERIC(2)     NOT NULL,
  ITEM_ATTR_TYPE_LENGTH           NUMERIC        DEFAULT 0                     NOT NULL,
  ITEM_ATTR_TYPE_ISSEARCHABLE     NUMERIC(1)     NOT NULL,
  ITEM_ATTR_TYPE_DISPLAY_INDEX    NUMERIC(2)     NOT NULL,
  ITEM_ATTR_TYPE_IS_REQUIRED      NUMERIC(1)     NOT NULL,
  ITEM_ATTR_TYPE_IS_METAPHONEKEY  NUMERIC        NOT NULL,
  ITEM_ATTR_TYPE_METAPHONEKEYPOS  NUMERIC,
  ITEM_ATTR_TYPE_LOOKUP_LIST_ID   VARCHAR(32),
  ITEM_TYPE_ID                    VARCHAR(32) NOT NULL,
  PRIMARY KEY(ITEM_ATTR_TYPE_ID)
);


CREATE TABLE ITEM_ATTR_TYPE_DATATYPE
(
  ITEM_ATTR_TYPE_DATATYPE_CODE  NUMERIC(2),
  ITEM_ATTR_TYPE_DATATYPE_NAME  VARCHAR(32) NOT NULL,
  ITEM_ATTR_TYPE_DATATYPE_DESC  VARCHAR(64),
  REGEX_PATTERN                 VARCHAR(256),
  PRIMARY KEY(ITEM_ATTR_TYPE_DATATYPE_CODE)
);




CREATE TABLE ITEM
(
  ITEM_ID                    VARCHAR(32)  NOT NULL,
  ITEM_CODE                  VARCHAR(64)  NOT NULL,
  ITEM_NAME                  VARCHAR(256),
  ITEM_DESC                  VARCHAR(256),
  ITEM_TYPE_ID               VARCHAR(32)  NOT NULL,
  ITEM_METAPHONE_SRC_STRING  VARCHAR(256),
  ITEM_METAPHONE_KEY         VARCHAR(64),
  PRIMARY KEY(ITEM_ID)
);


CREATE UNIQUE INDEX PK_IMPORT_JOBS ON IMPORT_JOBS
(FILENAME);


CREATE UNIQUE INDEX ITEM_PK ON ITEM
(ITEM_ID)
;


CREATE INDEX ITEM_METAPHONE_IDX ON ITEM
(ITEM_METAPHONE_KEY);

CREATE UNIQUE INDEX ITEM_PERF1_IDX ON ITEM
(ITEM_TYPE_ID, ITEM_ID);


CREATE UNIQUE INDEX ITEM_ATTRIBUTE_PK ON ITEM_ATTRIBUTE
(ITEM_ATTR_ID);


CREATE INDEX IDX3 ON ITEM_ATTRIBUTE
(ITEM_ATTR_TYPE_ID, "ITEM_ATTR_VALUE");



CREATE UNIQUE INDEX IDX_ATTR_PERF ON ITEM_ATTRIBUTE
(ITEM_ID, ITEM_ATTR_ID, ITEM_ATTR_TYPE_ID);


CREATE UNIQUE INDEX ITEM_ATTRIBUTE_TYPE_PK ON ITEM_ATTRIBUTE_TYPE
(ITEM_ATTR_TYPE_ID);



CREATE UNIQUE INDEX PK_ITEM_ATTR_TYPE_DATATYPE ON ITEM_ATTR_TYPE_DATATYPE
(ITEM_ATTR_TYPE_DATATYPE_CODE);


CREATE UNIQUE INDEX PK_ITEM_RELATIONSHIP_RULE_BASE ON ITEM_RELATIONSHIP_RULE_BASE
(ITEM_REL_RULE_BASE_ID);


CREATE UNIQUE INDEX ITEM_REL_RULE_IDX1 ON ITEM_RELATIONSHIP_RULE_BASE
(SOURCE_ITEM_TYPE_ID, TARGET_ITEM_TYPE_ID, REL_TYPE_ID);


CREATE UNIQUE INDEX ITEM_TYPE_PK ON ITEM_TYPE
(ITEM_TYPE_ID);


CREATE UNIQUE INDEX ITEM_TYPE_CODE_IDX ON ITEM_TYPE
(ITEM_TYPE_CODE);


CREATE UNIQUE INDEX RELATIONSHIP_PK ON RELATIONSHIP
(REL_ID);


CREATE UNIQUE INDEX RELATIONSHIP_ATTRIBUTE_PK ON RELATIONSHIP_ATTRIBUTE
(REL_ATTR_ID);


CREATE UNIQUE INDEX RELATIONSHIP_ATTRIBUTE_TYPE_PK ON RELATIONSHIP_ATTRIBUTE_TYPE
(REL_ATTR_TYPE_ID);

CREATE UNIQUE INDEX RELATIONSHIP_MAPPING_PK ON RELATIONSHIP_MAPPING
(REL_ID, SOURCE_ITEM_ID, TARGET_ITEM_ID);


CREATE UNIQUE INDEX RELATIONSHIP_TYPE_PK ON RELATIONSHIP_TYPE
(REL_TYPE_ID);



-- ====================================





ALTER TABLE ITEM_ATTRIBUTE ADD CONSTRAINT ITEM_ATTR_R02 FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID);

ALTER TABLE ITEM_RELATIONSHIP_RULE_BASE ADD CONSTRAINT ITEM_REL_RULE_BASE_R01 FOREIGN KEY(SOURCE_ITEM_TYPE_ID) REFERENCES ITEM_TYPE(ITEM_TYPE_ID);

ALTER TABLE ITEM_RELATIONSHIP_RULE_BASE ADD CONSTRAINT ITEM_REL_RULE_BASE_R02 FOREIGN KEY(TARGET_ITEM_TYPE_ID) REFERENCES ITEM_TYPE(ITEM_TYPE_ID);

ALTER TABLE ITEM_RELATIONSHIP_RULE_BASE ADD CONSTRAINT ITEM_REL_RULE_BASE_R03 FOREIGN KEY(REL_TYPE_ID) REFERENCES RELATIONSHIP_TYPE(REL_TYPE_ID);

ALTER TABLE RELATIONSHIP_ATTRIBUTE_TYPE ADD CONSTRAINT RELATIONSHIP_ATTRIBUTE_TYPER01 FOREIGN KEY(REL_TYPE_ID) REFERENCES RELATIONSHIP_TYPE(REL_TYPE_ID); 

ALTER TABLE RELATIONSHIP ADD CONSTRAINT REL_R01 FOREIGN KEY(REL_TYPE_ID) REFERENCES RELATIONSHIP_TYPE(REL_TYPE_ID);

ALTER TABLE RELATIONSHIP_MAPPING ADD CONSTRAINT RELATIONSHIP_MAPPING_R01 FOREIGN KEY(SOURCE_ITEM_ID) REFERENCES ITEM(ITEM_ID);

ALTER TABLE RELATIONSHIP_MAPPING ADD CONSTRAINT RELATIONSHIP_MAPPING_R02 FOREIGN KEY(TARGET_ITEM_ID) REFERENCES ITEM(ITEM_ID); 

ALTER TABLE RELATIONSHIP_MAPPING ADD CONSTRAINT RELATIONSHIP_MAPPING_R03 FOREIGN KEY(REL_ID) REFERENCES RELATIONSHIP(REL_ID);

ALTER TABLE RELATIONSHIP_ATTRIBUTE ADD CONSTRAINT REL_ATTR_R01 FOREIGN KEY(REL_ID) REFERENCES RELATIONSHIP(REL_ID);

ALTER TABLE ITEM_ATTRIBUTE_TYPE ADD CONSTRAINT ITEM_ATTRIBUTE_TYPE_R03 FOREIGN KEY(ITEM_TYPE_ID) REFERENCES ITEM_TYPE(ITEM_TYPE_ID);

ALTER TABLE ITEM_ATTRIBUTE_TYPE ADD FOREIGN KEY(ITEM_ATTR_TYPE_DATATYPE_CODE) REFERENCES ITEM_ATTR_TYPE_DATATYPE(ITEM_ATTR_TYPE_DATATYPE_CODE);

ALTER TABLE ITEM_ATTRIBUTE_TYPE ADD FOREIGN KEY(ITEM_ATTR_TYPE_LOOKUP_LIST_ID) REFERENCES ITEM_TYPE(ITEM_TYPE_ID);

ALTER TABLE ITEM ADD CONSTRAINT ITEM_R01 FOREIGN KEY(ITEM_TYPE_ID) REFERENCES ITEM_TYPE(ITEM_TYPE_ID);

*/



